on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    name: main

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Cache Repository
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace

      - name: Checkout This
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
          path: '.'

      - name: Random Delay
        if: github.event_name != 'workflow_dispatch'
        run: |
          sleep $((RANDOM % 3600))

      - name: Update Data
        uses: './'
        with:
            session: ${{ secrets.SESSION }}
            rate: 1

      - name: Setup Commit This
        run: |
          git config --local user.email "bot@ust.space"
          git config --local user.name "UST Space Bot"
          git add .

      - name: Commit This
        continue-on-error: true
        # skip git hooks by -n
        run: |
          now=$(date +"%Y-%m-%d")
          git commit -a -m "update: $now" -n

      - name: Push This
        uses: ad-m/github-push-action@master
        with:
          directory: ${{ github.workspace }}
